FROM ubuntu:14.04

MAINTAINER shadow1163 (674602286@qq.com)

COPY sources.list /etc/apt/sources.list
#
#RUN apt-get update
RUN apt-get update && apt-get install -y libgtk2.0-dev pkg-config libatk1.0-dev  libpango1.0-dev libfreetype6-dev libglib2.0-dev libx11-dev libncurses5-dev libxpm-dev libltdl-dev python python-dev

COPY 
