version: '3.3'

services:
   db:
     image: mysql:latest
     volumes:
       - ./wp-data:/docker-entrypoint-initdb.d
       - datavolume:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
     ports:
       - 3306:3306
     command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
     ]
     networks:
       - wordpress-network

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wp-app:/var/www/html
     ports:
       - "8000:80"
     links:
       - db
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: password
     networks:
      - wordpress-network

networks:
  wordpress-network:
      driver: bridge
volumes:
  datavolume:
